config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'about', to: 'pages#about', as: 'about'

  resources :subs do
    resources :posts, only: [:index]
  end

  resources :disasters do
    resources :posts, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:index]
  end

  resources :comments, except: [:index]

  devise_for :users

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :submitter_id, :post_id, presence: true

  belongs_to(
    :submitter,
    foreign_key: :submitter_id,
    primary_key: :id,
    class_name: 'User'
  )

  belongs_to(
    :post,
    foreign_key: :post_id,
    primary_key: :id,
    class_name: 'Post',
    counter_cache: true
  )

  belongs_to(
    :parent_comment,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    class_name: 'Comment'
  )

  has_many(
    :comments,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    class_name: 'Comment',
    dependent: :destroy
  )
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :must_be_commenter, only: [:destroy, :update, :edit]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    @comment.parent_comment_id = params[:parent_comment_id]
  end

  # GET /comments/1/edit
  def edit
    @comment = current_user.comments.find(params[:id])
    @post = Post.find(@comment.post_id)
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: post_path(@comment.post_id) }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment = current_user.comments.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@comment.post_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: post_path(@comment.post_id) }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def must_be_commenter
    comment = Comment.find(params[:id])
    unless current_user == comment.submitter
      render json: {msg: "You aren't the poster of this comment."}, status: 401
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.hidden_field :post_id
    = f.hidden_field :parent_comment_id

  .form-actions
    = f.button :submit

app/views/comments/edit.html.haml
- title(@post.title)

%div.well
  = render 'form'

= link_to 'Back', post_path(@post)

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
- title(@post.title)

= link_to post_path(@post), class:"btn btn-default" do
  %i.fa.fa-arrow-left
  Back

.well
  = render 'form'

app/views/comments/show.html.haml
= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path