config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'about', to: 'pages#about', as: 'about'

  resources :subs do
    resources :posts, only: [:index]
  end

  resources :disasters do
    resources :posts, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:index]
  end

  resources :comments, except: [:index]

  devise_for :users

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title,
            :description,
            :moderator_id,
            presence: true

  belongs_to(
      :moderator,
      foreign_key: :moderator_id,
      primary_key: :id,
      class_name: 'User'
  )

  has_many(
      :posts,
      foreign_key: :sub_id,
      primary_key: :id,
      class_name: 'Post',
      dependent: :destroy
  )

  scope :with_disaster, -> {
    where(:disaster => true)
  }

  scope :without_disaster, -> {
    where(:disaster => false)
  }

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :must_be_moderator, only: [:edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.without_disaster.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    @sub = Sub.includes(:moderator).friendly.find(params[:id])
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
    @sub = Sub.friendly.find(params[:id])
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = current_user.owned_subs.new(sub_params)

    respond_to do |format|
      if @sub.save
        format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.json { render :show, status: :created, location: @sub }
      else
        format.html { render :new }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    @sub = Sub.friendly.find(params[:id])
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub = Sub.friendly.find(params[:id])
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def must_be_moderator
    sub = Sub.friendly.find(params[:id])
    unless current_user == sub.moderator
      render json: {msg: "You aren't the moderator of this sub."}, status: 401
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.haml
= simple_form_for(@sub) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/subs/edit.html.haml
- title("Editing sub")

= link_to subs_path, class:"btn btn-default" do
  %i.fa.fa-arrow-left
  Back

%div.well
  = render 'form'

app/views/subs/index.html.haml
- title("Subs")

- @subs.each do |sub|
  .well
    %paper-card{:heading => "#{sub.title}"}
      .card-content
        = sub.description
      .card-actions
        = link_to sub_path(sub) do
          %paper-button
            Show
        - if user_signed_in?
          - if sub.moderator_id == current_user.id
            = link_to edit_sub_path(sub) do
              %paper-button
                Edit
            = link_to sub, :method => :delete, :data => { :confirm => 'Are you sure?' } do
              %paper-button
                Destroy

.well
  = link_to new_sub_path do
    %paper-button{:raised => ""}
      New Sub

app/views/subs/new.html.haml
- title("New sub")

%div.well
  = render 'form'

= link_to 'Back', subs_path

app/views/subs/show.html.haml
- title(@sub.title)

= link_to subs_path, class:"btn btn-default" do
  %i.fa.fa-arrow-left
  Back

- if user_signed_in?
  - if @sub.moderator_id == current_user.id
    = link_to edit_sub_path(@sub), class:"btn btn-default" do
      %i.fa.fa-edit
      Edit

- @sub.posts.each do |post|
  .well
    %paper-card{:heading => "#{post.title}"}
      .card-content
        = post.content
      .card-actions
        - unless post.url.nil?
          = link_to post.url do
            %paper-button
              Media
        = link_to post_path(post) do
          %paper-button
            Discussion

.well
  = link_to new_post_path(sub_id: @sub) do
    %paper-button{:raised => ""}
      New Post