config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'about', to: 'pages#about', as: 'about'

  resources :subs do
    resources :posts, only: [:index]
  end

  resources :disasters do
    resources :posts, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:index]
  end

  resources :comments, except: [:index]

  devise_for :users

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, :submitter_id, presence: true

  belongs_to(
      :sub,
      foreign_key:  :sub_id,
      primary_key:  :id,
      class_name: 'Sub'
  )

  belongs_to(
      :submitter,
      foreign_key:  :submitter_id,
      primary_key:  :id,
      class_name: 'User'
  )

  has_many(
      :comments,
      foreign_key:  :post_id,
      primary_key:  :id,
      class_name: 'Comment',
      dependent: :destroy
  )
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :must_be_poster, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:submitter).find(params[:id])
  end

  # GET /posts/new
  def new
    sub = Sub.friendly.find(params[:sub_id])
    @subtitle = sub.title
    @post ||= sub.posts.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def must_be_poster
    post = Post.find(params[:id])
    unless current_user == post.submitter
      render json: {msg: "You aren't the poster of this post."}, status: 401
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :url
    = f.input :content
    = f.hidden_field :sub_id

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
- title("Editing post")

%div.well
  = render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
- title("Front Page")
- @posts.each do |post|
  .well
    %paper-card{:heading => "#{post.title}"}
      .card-content
        = post.content
      .card-actions
        = link_to post.url do
          %paper-button
            Media
        = link_to post_path(post) do
          %paper-button
            Discussion
        - if user_signed_in?
          - if post.submitter_id == current_user.id
            = link_to edit_post_path(post) do
              %paper-button
                Edit
            = link_to post, :method => :delete, :data => { :confirm => 'Are you sure?' } do
              %paper-button
                Destroy
      .card-actions
        - if post.sub.has_attribute?(:disaster => true)
          = link_to disaster_path(post.sub) do
            %paper-button
              = post.sub.title
        - else
          = link_to sub_path(post.sub) do
            %paper-button
              = post.sub.title

app/views/posts/new.html.haml
- title("Post on #{@subtitle}")

%div.well
  = render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
- title(@post.title)

- if @post.sub.has_attribute?(:disaster => true)
  = link_to disasters_path(@post.sub), class:"btn btn-default" do
    %i.fa.fa-arrow-left
      Back
- else
  = link_to sub_path(@post.sub), class:"btn btn-default" do
    %i.fa.fa-arrow-left
      Back

- if user_signed_in?
  - if @post.submitter_id == current_user.id
    = link_to edit_post_path(@post), class:"btn btn-default" do
      %i.fa.fa-edit
      Edit

- @post.comments.each do |comment|
  %div.well
    %sp-chat-list{username: comment.submitter.username,
                  text: comment.content}
    - if user_signed_in?
      - if comment.submitter_id == current_user.id
        = link_to 'Edit Comment', edit_comment_path(comment)
    = link_to 'Reply', new_comment_path(post_id: @post, parent_comment_id: comment.id)

.well
  = link_to new_comment_path(post_id: @post) do
    %paper-button{:raised => ""}
      New Comment