config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'about', to: 'pages#about', as: 'about'

  resources :subs do
    resources :posts, only: [:index]
  end

  resources :disasters do
    resources :posts, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:index]
  end

  resources :comments, except: [:index]

  devise_for :users

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if !user_signed_in?
  %paper-item
    = link_to new_user_session_path do
      %i.fa.fa-sign-in.fa-lg
      Log in
  %paper-item
    = link_to new_user_registration_path do
      %i.fa.fa-user-plus.fa-lg
      Sign up
- else
  %paper-item
    = link_to edit_user_registration_path do
      %i.fa.fa-edit.fa-lg
      Edit my account
  %paper-item
    = link_to destroy_user_session_path, data:{method: :delete} do
      %i.fa.fa-sign-out.fa-lg
      Sign out
  %paper-item
    = link_to conversations_path do
      %i.fa.fa-inbox.fa-lg
      Inbox

%paper-item
  = link_to subs_path do
    %i.fa.fa-comments-o.fa-lg
    Subs
%paper-item
  = link_to disasters_path do
    %i.fa.fa-exclamation-triangle.fa-lg
    Disasters
%paper-item
  = link_to about_path do
    %i.fa.fa-info-circle.fa-lg
    About

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, minimum-scale=1.0, initial-scale=1", name: "viewport"}/
    %title= @title || "Sour Plum"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = html_import_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.fullbleed.vertical.layout
    %paper-drawer-panel.flex
      %paper-header-panel{:mode => "scroll", :drawer => ""}
        %paper-toolbar.tall#navheader
          %iron-image#coverimage.fit{:placeholder => image_url("beach.jpg"), :preload => "", :fade => "", :sizing => "cover"}
          - if !user_signed_in?
            %img.middle.profile{:src => image_url("avatar.png")}
          - else
            = image_tag avatar_url(current_user), class: "middle profile"
          %div.bottom.layout.vertical
            - if !user_signed_in?
              %span Anon
            - else
              %span
                = current_user.username
              %span
                = current_user.email
        = render 'layouts/navigation'
      %paper-header-panel{:main => ""}
        %paper-toolbar
          %paper-icon-button{:icon => "menu", 'paper-drawer-toggle' => ""}
          %span.title.indent
            = @title
        = yield